server:
  port: '8093'

spring:
  application:
    name: fees
  profiles:
    active: ${PROFILE:dev}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: 'true'
    restart:
      enabled: 'true'
